dist: trusty
language: java
sudo: false
jdk:
  - oraclejdk9
  - oraclejdk8
  - openjdk8
  - openjdk7

git:
  depth: 2 #clone repository to a maximum depth of 2 commits

script: "mvn clean verify"

after_success:
  #- mvn clean integration-test