dist: trusty
language: java
sudo: false
jdk:
  - oraclejdk8

git:
  depth: 2 #clone repository to a maximum depth of 2 commits

# git strips the wrapper jar file so we have to force its download during the build
install:
  - mvn -N io.takari:maven:wrapper
  - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

env:
  global:
    - CODECOV_TOKEN=:uuid-repo-token

after_success:
  - mvn clean integration-test
  - bash <(curl -s https://codecov.io/bash)