dist: trusty
language: java
sudo: false
jdk:
  - oraclejdk8

git:
  depth: 2 #clone repository to a maximum depth of 2 commits

script: "mvn clean install -Dmaven.javadoc.skip=true -B -V"

env:
  global:
    - CODECOV_TOKEN=:uuid-repo-token
before_install:
  - chmod +x mvnw

after_success:
  - mvn clean integration-test
  - bash <(curl -s https://codecov.io/bash) -t 4934d03c-5850-4c72-a2d3-1a3c7407fd99